name: google-cloud
mapping:
  af: afr
  sq: sqi
  am: amh
  ar: ara
  hy: hye
  az: aze
  eu: eus
  be: bel
  bn: ben
  bs: bos
  bg: bul
  ca: cat
  ceb: ceb
  ny: UNK-ny  # Chichewa, Chewa, Nyanja
  zh: zho
  zh-TW: lzh
  co: cos
  hr: hrv
  cs: ces
  da: dan
  nl: nld
  en: eng
  eo: epo
  et: est
  tl: tgl
  fi: fin
  fr: fra
  fy: fry
  gl: glg
  ka: kat
  de: deu
  el: ell
  gu: guj
  ht: hat
  ha: hau
  haw: UNK-haw  # Hawaiian
  iw: heb
  hi: hin
  hmn: UNK-hmn  # Hmong
  hu: hun
  is: isl
  ig: ibo
  id: ind
  ga: gle
  it: ita
  ja: jpn
  jw: jav
  kn: kan
  kk: kaz
  km: khm
  ko: kor
  ku: kur
  ky: kir
  lo: lao
  la: lat
  lv: lav
  lt: lit
  lb: ltz
  mk: mkd
  mg: mlg
  ms: msa
  ml: mal
  mt: mlt
  mi: mri
  mr: mar
  mn: mon
  my: mya
  ne: nep
  'no': nob
  ps: pus
  fa: fas
  pl: pol
  pt: por
  pa: pan
  ro: ron
  ru: rus
  sm: UNK-sm  # Samoan (sm)
  gd: gla
  sr: srp
  st: UNK-st  # Southern Sotho
  sn: sna
  sd: snd
  si: sin
  sk: slk
  sl: slv
  so: som
  es: spa
  su: sun
  sw: swa
  sv: swe
  tg: tgk
  ta: tam
  te: tel
  th: tha
  tr: tur
  uk: ukr
  ur: urd
  uz: uzb
  vi: vie
  cy: cym
  xh: xho
  yi: yid
  yo: yor
  zu: UNK-zu  # Zulu