mapping:
  af: afr
  am: amh
  an: arg
  ar: ara
  as: asm
  az: aze
  be: bel
  bg: bul
  bn: ben
  br: bre
  bs: bos
  ca: cat
  cs: ces
  cy: cym
  da: dan
  de: deu
  dz: UNK  # dzo
  el: ell
  en: eng
  eo: epo
  es: spa
  et: est
  eu: eus
  fa: fas
  fi: fin
  fo: fao
  fr: fra
  ga: gle
  gl: glg
  gu: guj
  he: heb
  hi: hin
  hr: hrv
  ht: hat
  hu: hun
  hy: hye
  id: ind
  is: isl
  it: ita
  ja: jpn
  jv: jav
  ka: kat
  kk: kaz
  km: khm
  kn: kan
  ko: kor
  ku: kur
  ky: kir
  la: lat
  lb: ltz
  lo: lao
  lt: lit
  lv: lav
  mg: mlg
  mk: mkd
  ml: mal
  mn: mon
  mr: mar
  ms: msa
  mt: mlt
  nb: nob
  ne: nep
  nl: nld
  nn: nno
  "no": nno
  oc: oci
  or: ori
  pa: pan
  pl: pol
  ps: pus
  pt: por
  qu: que
  ro: ron
  ru: rus
  rw: kin
  se: sme
  si: sin
  sk: slk
  sl: slv
  sq: sqi
  sr: srp
  sv: swe
  sw: swa
  ta: tam
  te: tel
  th: tha
  tl: tgl
  tr: tur
  ug: uig
  uk: ukr
  ur: urd
  vi: vie
  vo: vol
  wa: wln
  xh: xho
  zh: zho
  zu: UNK  # zul